### ISSUE TITLE
div#rikaichamp-window interferes with website in unexpected ways

### ISSUE THREAD

**Issue by mortenn** [birtles/rikaichamp#14]
I was noticing some issues with image links not being clickable, and hover effects not working for part of a div in the chatbox on plug.dj
When I right click an unresponsive screen section and inspect, I got to a div with the id rikaichamp-window
This was while rikaichamp was disabled.

**Comment by birtles** [comment]
Oh, that sounds bad. If rikaichamp was simply not showing the pop-up I could understand that happening because, for example, maybe we forgot to set `pointer-events: none` (actually, it appears this is the case so I should fix that asap).

However, if rikaichamp is _disabled_, i.e. the button is grey, that sounds like we're failing to remove the element which shouldn't happen normally. Perhaps it happened when the add-on was upgraded? Maybe we need to watch for uninstall events and be sure to clear the window then.

**Comment by birtles** [comment]
I released two updates over the weekend so there's a chance it was upgraded. But when you say disabled do you mean?

a) No pop-up is showing?
b) You turned the add-on off using the toolbar / context-menu / shortcut key?
c) You disabled the add-on using the Firefox add-on panel?

Unfortunately for (c) at least there's nothing the add-on can do. But for all cases the changes I made a1d4492d971cae5c9413094f2317b8ffedffc698 should fix things (the element won't be removed, but it won't interfere with anything either)ーonce that gets released.

**Comment by mortenn** [comment]
The addon was running, with the toolbar button grayed out.
I've not enabled/disabled the addon through any other means than restarting firefox or clicking the button.

The commit looks good to me :) I don't really mind the div being there so long as it won't break websites.

**Comment by birtles** [comment]
Great, thank you.

I've confirmed that that commit also fixes the issues I was seeing with Gmail so I'll try to release it soon-ish.
