### ISSUE TITLE
Add other languages than English

### ISSUE THREAD

**Issue by Sesshu** [birtles/rikaichamp#16]
Currently I can only access the JPN-ENG dictionary. I can't find a way to access or install any other dictionaries like Rikaichan has such as JPN-GER. Is there a way to add other languages? If not, please add this feature.

**Comment by birtles** [comment]
There's currently no way to add other dictionaries. I'm afraid that could take a while before that is supported since I first need to change the way the dictionary is downloaded so that it is synchronized separately from the add-on.

**Comment by Lebon14** [comment]
I think they should be different addons. The current addon should be "Japanese English". If multiple addons are downloaded and are conflicting, a simple "please desactivate any extra addons before using "rikaichamp LangX LangY". I don't know how feasible a switcher is (imagine the current icon but when you click it, it shows the different addons installed).

I personally only use Japanese though.

My 2¢.

**Comment by birtles** [comment]
Long-term I'd like to store the dictionary as a separate IndexedDB database. That way it would be faster to lookup, wouldn't require generating separate indices, wouldn't require loading the whole thing into memory on startup (making the addon startup faster and not hog memory) and it would be possible to do a minimal sync when updating so that updating could potentially happen every day. (The main difficulty is that most CouchDB servers cost money after a certain level of traffic and I hope I wouldn't have to foot a big bill.)

After that is done it would be easier to support separate dictionaries and let the user download the ones they need.

**Comment by nicolasmaia** [comment]
Any news on the IndexedBD database work?

**Comment by birtles** [comment]
Yes, it's still moving along well. The kanji data is already in IndexedDB and is downloaded out-of-band. Patch files are generated each day there are updates. For this kanji data, you can choose the database language already in the options (when you change it the new language files are downloaded).

I recently rewrote the whole backend for generating the files so next I will move the names database over to this setup, then finally the word database. So there's probably at least 2 months work left, possibly more.

**Comment by nicolasmaia** [comment]
がんばって！

**Comment by birtles** [comment]
As of version 0.4.0 this is finally done. Sorry for the delay!
