### ISSUE TITLE
Idea: translate Netflix subtitles

### ISSUE THREAD

**Issue by picsi** [birtles/rikaichamp#218]
I'm not sure how viable it is, but it would be awesome and extremely useful if it can be done.

**Comment by siikamiika** [comment]
The issue here is that Netflix uses image subtitles by default for CJK text (at least in non-Asian countries), and popup dictionaries can't process them. There's a workaround for this that uses the Netflix API:
https://chrome.google.com/webstore/detail/subadub/jamiekdimmhnnemaaimmdahnahfmfdfk
https://addons.mozilla.org/en-US/firefox/addon/subadub/

**Comment by picsi** [comment]
@siikamiika This is excellent, thanks!
