### ISSUE TITLE
Romaji Support?

### ISSUE THREAD

**Issue by japzone1** [birtles/rikaichamp#23]
Can you add romaji support?

**Comment by birtles** [comment]
That sounds very do-able and useful. I'm afraid it not high on my priorities yet (fixing text selection is more important) but perhaps someone else will submit a PR.

**Comment by japzone1** [comment]
Thanks for the consideration. This is the one thing I'm missing from my old
add-on.

On Dec 15, 2017 10:37 AM, "Brian Birtles" <notifications@github.com> wrote:

That sounds very do-able and useful. I'm afraid it not high on my
priorities yet (fixing text selection is more important) but perhaps
someone else will submit a PR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/birtles/rikaichamp/issues/23#issuecomment-352035816>,
or mute the thread

**Comment by japzone1** [comment]
Any update on this?

**Comment by birtles** [comment]
I'm afraid not. Are you able to contribute a patch for this?

**Comment by birtles** [comment]
This should be mostly done now in https://github.com/birtles/rikaichamp/commit/1161d2868c5d6d36b85c7e901eb6ea95eda7365a and https://github.com/birtles/rikaichamp/commit/10583de4c7a9fdd6266fd13c9dae52c4145c8c8f .

I probably want to test it a bit more before releasing however.

**Comment by japzone1** [comment]
Thanks for not forgetting about this functionality. I look forward to trying it out once it's available.

**Comment by birtles** [comment]
I think it's mostly ready. I'm just wondering if instead of allowing _both_ the kana and the romaji if the option should just be to allow one or the other. I wonder if anyone actually needs both.

![image](https://user-images.githubusercontent.com/1232595/60792684-1bd10300-a1a1-11e9-897c-589663af6dad.png)

(To be honest it's a little easier to allow both but I suspect it's less user-friendly that way.)

**Comment by japzone1** [comment]
Personally, I prefer both, but there are probably people that want to disable one or the other.

**Comment by birtles** [comment]
Yeah, I can see having both being useful for folks learning hiragana as well. I might just release it without the option of turning off the hiragana and wait for people to ask for it.

(I really want to avoid having too many options since it makes the whole extension more complicated to use and harder to maintain. And as they say, "options are the refuge of the weak" 😉)

**Comment by japzone1** [comment]
Fair enough 😆 

There probably won't be too many people complaining anyway as long as the romaji doesn't get in the way of any of the existing information. Though I have met people that will complain just because something exists, even if it doesn't affect anything they originally had.....

**Comment by birtles** [comment]
Ok this should be available now under version 0.0.32. It's off by default, however, so you'll need to go to the options page to turn it on.
