### ISSUE TITLE
Continuative form

### ISSUE THREAD

**Issue by Kala-J** [birtles/rikaichamp#245]
Is there a way to recognize verbs in continuative form (連用形)? For example, I encountered this phrase in a novel:

こらえきれなくなって

The こらえ is not recognized as the 連用形 of こらえる, but a site like [ichi.moe](https://ichi.moe/cl/qr/?q=%E3%81%93%E3%82%89%E3%81%88%E3%81%8D%E3%82%8C%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%A3%E3%81%A6&r=htr) has no issues parsing it.

**Comment by birtles** [comment]
That's odd. I thought that was supported but it's clearly not working (e.g. 食べ also doesn't work). That might be a regression.

(For that particular case, it might also be worth adding special handling for the ~きれる suffix. That would give you more useful information than what ichi.moe is giving you since the actual meaning in that context doesn't appear until point 16 of the list of definitions of 切る.)

**Comment by birtles** [comment]
I suspect 529c15529611a29d2fb07d59e6677d29276e1fa3 broke this.
