### ISSUE TITLE
No or wrong target for popup

### ISSUE THREAD

**Issue by kikaxa** [birtles/rikaichamp#29]
http://nec-lavie.jp/products/nm/
for the left-sided ad paragraphs (外出先でも、...)
also seems somewhat related to #27 and #11

**Comment by birtles** [comment]
I had a brief look at this and it turns out an ancestor of that text is transformed (translate only) and in that case `caretPositionFromPoint` always gives us back an offset of zero. So this is very much like #27. I wonder what we can do about it.

We could, I suppose, untransform the content, apply the inverse transformation to the mouse coordinates, call `caretPositionFromPoint`, then restore the transform, but that sounds like a major perf hit since transforms are used frequently. First we probably need to verify that this does affect all transformed content and look into if it's worthwhile fixing on the Gecko side.

**Comment by kikaxa** [comment]
the initial patch tried to reverse transforms but committed one was different. that was 7! years ago.
talk about good testing...

https://bugzilla.mozilla.org/show_bug.cgi?id=654352
https://dxr.mozilla.org/mozilla-central/source/dom/base/nsDocument.cpp
https://dxr.mozilla.org/mozilla-central/source/dom/base/nsDOMCaretPosition.cpp

**Comment by birtles** [comment]
This is [Firefox bug 1025815](https://bugzilla.mozilla.org/show_bug.cgi?id=1025815).

**Comment by kikaxa** [comment]
Seems this bug has some progress now.

**Comment by birtles** [comment]
[Bug 1025815](https://bugzilla.mozilla.org/show_bug.cgi?id=1025815) has landed in Firefox Nightly and I confirm that this bug is fixed in Firefox 62!
