### ISSUE TITLE
Feature request: a way to turn off the name preview feature

### ISSUE THREAD

**Issue by smarter** [birtles/rikaichamp#372]
Recently, rikaichamp has started displaying results from the name dictionary by default (https://github.com/birtles/rikaichamp/commit/e8d61d865964e2bdf0fd0be92a729b8e5440177f, https://github.com/birtles/rikaichamp/commit/37007e16aed62d22c511292108c360cfe8645c08), I can see how that could be useful but I personally find it a bit too distracting and would appreciate an option for turning this off.

**Comment by melink14** [comment]
Interesting. As a bystander, I assumed it would always be a net win since
it only shows up if there wouldn't have been a match.

Are you finding it shows up often when the text wasn't referring to a name?

**Comment by smarter** [comment]
I haven't used irikaichamp enough recently to say how common it is, but here's an example:
![rikai](https://user-images.githubusercontent.com/63430/92661635-54b4bc80-f2fd-11ea-8748-4734fb7fffd9.png)

**Comment by smarter** [comment]
Maybe the name preview should only trigger if the matched string is written entirely in kanji?

**Comment by melink14** [comment]
Interesting example and heuristic.

I agree that would be right most of time though there are actually a lot of foreign place names that don't use Kanji of course (interested to see the false positive rate there...)

**Comment by nicolasmaia** [comment]
Maybe kanji and katakana can have a higher priority?

**Comment by birtles** [comment]
Yes, I'm in favor of tweaking the heuristic as opposed to adding a pref (most people will never find the pref, and the example you gave is likely to bother everyone, so we should fix it for everyone without making them turn off the name preview feature altogether).

I agree that the name entries that we want to surface in the preview are likely to be when we match on at least some kanji or katakana. Purely hiragana matches a more likely to be false positives. That seems like a good adjustment to the heuristic.

Other things we could do to mitigate the annoyance, apart from tweaking the heuristic are:

* Reduce the number of kanji versions we show in the preview (e.g. just show 沖野、坂野、中堅… for the first example above). There is already a flag for this so it would be easy to tweak. That said, that sort of grouping only tends to happen when we match on hiragana anyway so maybe that's not needed.
* Only show the first match plus … instead of up to 3 matches.
