### ISSUE TITLE
Which words are marked popular has changed to be less accurate (indifferent to kanji, seemingly)

### ISSUE THREAD

**Issue by Lyrencropt** [birtles/rikaichamp#437]
Previously, Rikaichamp used to show a (P) tag if a word was marked as "popular" according to EDICT. I found this very useful, and it was one of the main things I looked for. It doesn't seem to be there in the newest release, and I'm unsure if this is intentional.

**Comment by birtles** [comment]
Hi! Yes, that (P) tag has been replaced by the ★ mark next to the readings / headwords that are popular. The ☆ mark indicates a less common word but one that is still somewhat common.

**Comment by Lyrencropt** [comment]
I see. Are these coming from the same source? I see some words marked with a star that I don't think really should, like 効(かい). 
![image](https://user-images.githubusercontent.com/1493982/100396196-1922b800-2ff9-11eb-86ed-3ba3bbfa8ac4.png)

**Comment by Lyrencropt** [comment]
Downgraded my version and yeah, 効 was not marked (P) in the previous version. Only 甲斐 was.
![image](https://user-images.githubusercontent.com/1493982/100396492-14aacf00-2ffa-11eb-8406-6b5e5feae725.png)
![image](https://user-images.githubusercontent.com/1493982/100396516-2b512600-2ffa-11eb-83e8-a9177789b5cf.png)

This seems like a regression?

**Comment by birtles** [comment]
Yes, they are coming from the same source.

(Previously we used the EDICT data source which marks certain entries with (P) based on if the source in JMdict has certain priority tags. We now use JMdict data directory but we match the same mapping as used in EDICT.)

In that example, the ★ is next to the かい so it is indicating that "かい" as a word is common. However, there is no ★ next to 効 because it is not common. If you hover over 甲斐 you will see that there is a ★ next to the kanji headword as well.

**Comment by Lyrencropt** [comment]
I see, alright. I'll go ahead and close this out then. This is a very large change, is there some simple explanation of everything that was changed with 0.3?

**Comment by birtles** [comment]
The [changelog](https://github.com/birtles/rikaichamp/blob/main/changelog.md) gives a brief summary.

Beyond what's listed there, the other main change is that entries are now grouped together. So, for example, when matching in kana, rather than listing several identical entries for each possible kanji headword, they now appear as one entry.

Also, definitions are displayed as a numbered list.

Regarding the confusion surrounding ★. Currently we only show the matching kanji headword. We _could_ show all the kanji headwords for the entry.  That would give you something like:

  甲斐 ★、詮、効　かい ★

Which would probably be more clear. However, it would clutter things a bit too.

**Comment by Lyrencropt** [comment]
Sure. This all makes sense, I'm also just very used to seeing the same thing for like... god, ten years now, and suddenly I moused over something and everything was different 😅 

The joys of automatic extension updates...

Thank you for all your hard work.

**Comment by birtles** [comment]
Sorry to surprise you like that! I hope we can make the new display even more useful. Let me know if you think that displaying all the kanji headwords would be better and I'll give it a try.

This whole change is really just part of the process of getting the extension ready to support automatic dictionary updates and multi-lingual glosses (hopefully next month).

**Comment by Lyrencropt** [comment]
I think I would prefer it, but I also think I'll probably get used to whatever it is, as long as the information is there. Even after ten years I of using it, I regularly mix(ed) up "uk" and "uK", so this is clearly better already.

**Comment by birtles** [comment]
Ok, thank you! Let me try it some time and see how it feels.
