### ISSUE TITLE
Add pitch-accent pattern

### ISSUE THREAD

**Issue by YoruNoHikage** [birtles/rikaichamp#48]
One feature that would be nice to have is having little dots either high or low depending on the pitch pattern or just the number that is corresponding to that pattern the same way. I don't own a mac but I know for sure the built-in dictionary supports it.

![Pitch patterns](https://i.imgur.com/oEjxhWU.jpg)

I would be glad to contribute but I have no idea if the current dictionaries have already those informations or how to read them.

**Comment by birtles** [comment]
Yeah, I think finding a suitable source for the data is the chief problem. Perhaps with EPWING support we could do it, but each user would need to purchase the NHK 日本語発音アクセント辞典 themselves.

(I also remember the teacher at the pronunciation school I attended here in Tokyo saying that chart was wrong, that no one ever speaks like that. So I'm a little conflicted about this. If there's suitable data though I'm happy to add it as an option.)

**Comment by shibotto** [comment]
Can the one Yomichan recently implemented be useful?
https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary

**Comment by birtles** [comment]
> Can the one Yomichan recently implemented be useful?
> https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary

Technically it seems straightforward, but unfortunately it's not completely clear where that data originally comes from. The original repo (https://github.com/mifunetoshiro/kanjium) seems to claim credit for it but I'm a little concerned it's been derived from elsewhere. If anyone has any extra information that would be good!

**Comment by smarter** [comment]
Would it be less concerning if the data was downloaded when the pitch accent option is enabled by the user instead of distributing it with the extension?

**Comment by birtles** [comment]
I dug into this a couple of weeks ago and the format and values are sufficiently different that I'm confident it's not duplicating the NHK pronunciation data, so that's a start. I'm still not sure what the original source is but for now I'll take the repository's word and treat it as original, freely available data.

I've already integrated it into the data set for the upcoming word database overhaul so hopefully this will be available in the next release early next month or so.

**Comment by birtles** [comment]
I've started fiddling with the display over in my test app:

![image](https://user-images.githubusercontent.com/1232595/96831135-7619d400-1477-11eb-814d-30d84adf300f.png)

If anyone wants to try it out and check the results look sane: https://hikibiki.app/?q=%E3%81%AF%E3%81%97
(You'll need to wait for the data files to be downloaded and applied though. Also, due to a quirk in the way that app works, you'll need to re-trigger the search after all the updates have been applied to get all the results.)

It's just using little arrows to mark the drop or a dotted line over the top to represent 平板. You can hover over the reading to get a description.

It doesn't currently expose the data in that file where there are annotations (e.g. the pitch differs for nouns). The data is there though, it's just a matter of deciding if/how to show it.

**Comment by smarter** [comment]
Nice!

> It's just using little arrows to mark the drop or a dotted line over the top to represent 平板. 

Personal preference but I like the way https://addons.mozilla.org/en-US/firefox/addon/pitcher/ displays the pitch with a red line (this is also commonly used on https://japanese.stackexchange.com/)

**Comment by birtles** [comment]
> Personal preference but I like the way https://addons.mozilla.org/en-US/firefox/addon/pitcher/ displays the pitch with a red line (this is also commonly used on https://japanese.stackexchange.com/)

Thanks! I looked at that but I wasn't sure how people use it. I notice sometimes the annotations sometimes go up in the middle of the word and that seems odd to me. My teacher at the pronunciation juku would have a fit if anyone suggested the intonation goes up in the middle of word!

**Comment by smarter** [comment]
> My teacher at the pronunciation juku would have a fit if anyone suggested the intonation goes up in the middle of word!

Apparently there's multiple views on the subject, section "Downstep" of https://en.wikipedia.org/wiki/Japanese_pitch_accent matches what you're saying, but "Binary pitch" is pretty common. I guess it's not a big deal either way.

**Comment by birtles** [comment]
> Apparently there's multiple views on the subject, section "Downstep" of https://en.wikipedia.org/wiki/Japanese_pitch_accent matches what you're saying, but "Binary pitch" is pretty common. I guess it's not a big deal either way.

Yeah, that very much aligns with his approach. I don't like adding options to Rikaichamp (more confusing, more to maintain, more to test, most people never discover them etc.) but toggling between those two might be a reasonable thing to add if many people are used to the binary pitch annotation.

**Comment by birtles** [comment]
This should be mostly done on the [`update-words` branch](https://github.com/birtles/rikaichamp/tree/update-words) now.

There's a toggle to change between showing the downstep or the up-down / binary pitch display. The binary pitch display looks like the following:

![image](https://user-images.githubusercontent.com/1232595/98884434-53f1ff80-24d3-11eb-857f-558cbd677aa0.png)

I've integrated the same toggle into [hikibiki](https://hikibiki.app/?q=%E3%81%AF%E3%81%97) for anyone who wants to try it there.

**Comment by birtles** [comment]
This should be available in the just-released v0.3.0.

**Comment by smarter** [comment]
Thank you!

**Comment by nicolasmaia** [comment]
Would it be possible to also enable this for the names dictionary?

**Comment by birtles** [comment]
In theory we can look for matches in the accent data but I'm not sure how many hits we'd get. I'm in the process of overhauling the data export pipeline so I'll give it a try then. It's a several month project, however.
