### ISSUE TITLE
Dictionary

### ISSUE THREAD

**Issue by marethyu** [birtles/rikaichamp#485]
I wonder if there’s a way to access the dictionary that rikaichamp uses? It’s really useful. I can’t install rikaichamp on chrome.

**Comment by birtles** [comment]
Hi Jimmy, thanks!
You can use the same dictionary at https://hikibiki.app. You will need to wait for it to download the data (since it all runs locally, as opposed to on the server) and it has a few bugs but I hope to fix them soon.
Also, I hope to make Rikaichamp work with Chrome in the next month or two.

**Comment by marethyu** [comment]
Thanks man!
