### ISSUE TITLE
Update zh-hans translation for new word dictionary

### ISSUE THREAD

**Issue by birtles** [birtles/rikaichamp#561]
I've merged the updated word dictionary handling into `main` now since it's (hopefully) nearly ready to ship.

However, we still need to update the zh-hans translation as follows:

* Update the `options_data_source` string from "Includes data from KANJIDIC and JMnedict/ENAMDICT." to "Includes data from JMdict/EDICT, KANJIDIC and JMnedict/ENAMDICT."
* Add the following strings:
  * `options_lang_kanji_only`
  * `options_lang_warning_always_en`
  * `options_lang_warning_change_lang_redownload`
  * `options_lang_warning_names_en_only`
  * `options_lang_warning_other_lang_when_available`
  * `options_lang_warning_please_note`
  * `options_lang_warning_temporary_en_fallback`
  * `options_lang_words_only`
  * `options_words_data_name`
  * `options_words_data_title`

`options_data_source` ends up being rendered like:

![image](https://user-images.githubusercontent.com/1232595/113657718-792d1780-96d9-11eb-87d3-5ba14c645765.png)

The list of warnings ends up looking like the following in Japanese:

![image](https://user-images.githubusercontent.com/1232595/113657528-1b98cb00-96d9-11eb-9ef4-61d40d5a5be1.png)

The words_only / kanji_only labels end up being rendered like:

![image](https://user-images.githubusercontent.com/1232595/113657571-30755e80-96d9-11eb-8d41-93ba250f0a7d.png)

`options_words_data_name` shows up here:

![image](https://user-images.githubusercontent.com/1232595/113657794-a8dc1f80-96d9-11eb-87c5-b210aff1fe5b.png)

`options_words_data_title` shows up here:

![image](https://user-images.githubusercontent.com/1232595/113657646-5569d180-96d9-11eb-9171-4ceb2be1f7e1.png)

@SaltfishAmi are you able to help with this?

**Comment by SaltfishAmi** [comment]
Sure, I can do this.SaltfishAmiSent from phone---- On Tue, 06 Apr 2021 12:13:50 +0800  ***@***.******@***.***> wrote ---- 
I've merged the updated word dictionary handling into main now since it's (hopefully) nearly ready to ship. 
However, we still need to update the zh-hans translation as follows: 
 
Update the options_data_source string from "Includes data from KANJIDIC and JMnedict/ENAMDICT." to "Includes data from JMdict/EDICT, KANJIDIC and JMnedict/ENAMDICT." 
Add the following strings: 
 
options_lang_kanji_only 
options_lang_warning_always_en 
options_lang_warning_change_lang_redownload 
options_lang_warning_names_en_only 
options_lang_warning_other_lang_when_available 
options_lang_warning_please_note 
options_lang_warning_temporary_en_fallback 
options_lang_words_only 
options_words_data_name 
options_words_data_title 
 
 
 
options_data_source ends up being rendered like: 
 
The list of warnings ends up looking like the following in Japanese: 
 
The words_only / kanji_only labels end up being rendered like: 
 
options_words_data_name shows up here: 
 
options_words_data_title shows up here: 
 
@SaltfishAmi are you able to help with this?

**Comment by birtles** [comment]
> Sure, I can do this.

Great! Thank you!

**Comment by SaltfishAmi** [comment]
I also suggest that in the Japanese version of `options_lang_warning_change_lang_redownload` we replace `再読み込み` with `再ダウンロード` because the first one could be misunderstood as 'reload from local disk'.

**Comment by birtles** [comment]
> I also suggest that in the Japanese version of `options_lang_warning_change_lang_redownload` we replace `再読み込み` with `再ダウンロード` because the first one could be misunderstood as 'reload from local disk'.

Fixed in ee53ed11534d141b451c64dd7bf5dce4bae53603
