### ISSUE TITLE
No translations displayed

### ISSUE THREAD

**Issue by tomtinker** [birtles/rikaichamp#57]
I have just installed Rikaichamp on Firefox 62 running Windows 10 English (on a new PC). Rikaichamp seems very handy for looking up the readings of kanji, but isn't it supposed to also display English translations? It only displays the readings of the kanji in kana. How do I get it to display translations as well?

**Comment by picsi** [comment]
I experienced this too! I came here to report it. Let's put another key before D, like Alt. Shift or Ctrl.

**Comment by birtles** [comment]
I was thinking that if we disable the shortcut by default then only users who have explicitly enabled it would find themselves pressing it--and hopefully they will then know what happened.

I actually don't know why anyone would disable the definitions, or why they would need a shortcut to be able to toggle them on/off quickly as opposed to just going to the options page and doing it. (Even the Japanese people I know who use Rikaichamp keep them on since they often want to look up English expressions.)
