### ISSUE TITLE
Boxes not displaying correctly

### ISSUE THREAD

**Issue by vaugemind727** [birtles/rikaichamp#576]
![Untitled](https://user-images.githubusercontent.com/57221809/115410084-3f383700-a1ea-11eb-8698-a717664c2aaa.png)

**Comment by SaltfishAmi** [comment]
Could you please provide some more details, like, where did you encounter this issue?

**Comment by vaugemind727** [comment]
It's only an issue when there is one line of text so it isn't that big a
deal actually.

Firefox
using a horizontal clipboard inserter ( vnhooking - visualnovels
<https://www.reddit.com/r/visualnovels/wiki/vnhooking>)

**Comment by birtles** [comment]
Yeah, there's something funny going on there. I wonder if it's the texthooker page actually clobbering the popup. It's using mutation events (which are deprecated) to detect inserted nodes and Rikaichamp inserts a node. I think after you move the mouse to a different part of the word it should work since it's no longer inserting a node (just updating the existing one).

![image](https://user-images.githubusercontent.com/1232595/115717836-87f01b80-a3b5-11eb-9f4e-f0e97c264171.png)

**Comment by birtles** [comment]
Ok, I dug into this some more and it turns out this is actually a bug arising because the Texthooker page is operating in quirks mode and the `clientHeight` returned on the document element there is different than in standards mode.

Should be fixed in the next release.
