### ISSUE TITLE
Bug: does not work for inputs and textareas in Google Chrome

### ISSUE THREAD

**Issue by emerencia** [birtles/rikaichamp#86]
Rikaichamp doesn't work for kanji in text inputs or textareas. It does work on kanji in other element son the same page.

I don't see any errors in the console, and I get the same behavior when I enable it to work in incognito mode and run the browser in incognito mode (which means it's the only extension running at that time), and then it still doesn't work in textareas/text inputs. This is on MacOs Mojave, Chrome v. 73.0.3683.56.

I just pulled the master branch to get the latest version of everything and ran the npm install and npm run build:chrome commands.

I made a small recording to illustrate the problem I'm having: https://streamable.com/n1yhc

**Comment by birtles** [comment]
This appears to be because Chrome doesn't support `carentPositionFromPoint` (only `caretRangeFromPoint`) and when I pass `caretRangeFromPoint` the coordinates of a text box, it returns the `<body>` element. That may be why rikaikun had to resort to temporarily creating fake elements to cover over text boxes (see https://github.com/melink14/rikaikun/issues/16#issuecomment-111650274).

I was really hoping not to re-introduce that (I'm afraid that manipulating the DOM like that will break some apps) but I might have to unless Chrome fix their bugs or [implement `caretPositionFromPoint`](https://bugs.chromium.org/p/chromium/issues/detail?id=388976). That's going to be a big project since I should probably drop all the existing text box handling from Rikaichamp at the same time so that both Firefox and Chrome end up using the same approach. Ugh.

**Comment by birtles** [comment]
This should now be fixed. You can give it a try at: https://chrome.google.com/webstore/detail/pnmaklegiibbioifkmfkgpfnmdehdfan

**Comment by emerencia** [comment]
Awesome! I'll check it out
