### ISSUE TITLE
Allow glossing of full width romaji

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#96]
Quite a few entries in JMdict contain either numbers or romaji. It'd be cool if this addon could parse those, or at least when they're in full width.

**Comment by birtles** [comment]
Yeah, I've thought about doing this but I've always felt uncomfortable about it only working when the text is full-width. Are there certain sites you use that actually write these words in full-width romaji?

Skimming through asahi.com right now I see:

* ＩＴ - Obvious / not Japanese-specific?
* ＡＩ - Obvious / not Japanese-specific?
* ＮＨＫ - Not in the dictionary as a separate entry so far as I can tell
* 野村ＨＤ - Not in the dictionary in sense used here (HD = Holdings)
* ＳＢ - SoftBank - not in the dictionary
* ＷＡＤＡ - World anti-doping agency - not in the dictionary
* ＶＳ - Versus - this one actually is in the dictionary and could be useful
* ＳＮＳ - This one too
* ＪＲ - This one too

So, I guess it would at least help with ＶＳ (since it might not be obvious in sentence 井山ＶＳ山下再び what it indicates) and ＳＮＳ / ＪＲ (since someone unfamiliar with Japan might not know those terms).

So maybe it's worth doing after all even if only for full-width text. I did see a few instances of half-width romaji too but working sometimes is probably better than never working.

**Comment by SaltfishAmi** [comment]
> 
> 
> Yeah, I've thought about doing this but I've always felt uncomfortable about it only working when the text is full-width. Are there certain sites you use that actually write these words in full-width romaji?
> So maybe it's worth doing after all even if only for full-width text. I did see a few instances of half-width romaji too but working sometimes is probably better than never working.

Alphanumerics in full-width give me a feeling of "Hey I'm a part of the Japanese language!",
While in half-width I'd regard them as western script
